steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        set -x && \
        gcloud compute ssh vending-machine --zone=europe-north1-a --command='/bin/sh /home/danylo_kovalchuk_ir_2021/starup.sh'
