steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: /home/danylo_kovalchuk_ir_2021
    args:
      - '-c'
      - |
        set -x && \
        gcloud compute ssh vending-machine --zone=europe-north1-a --command='startup.sh'
